name: Async Build Script

on:
  push: {}
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 22
        java-package: jdk

    - name: Install required dependencies
      run: sudo apt update && sudo apt install libtinfo5

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
    
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ./.gradle/loom-cache
        key: ${{ runner.os }}-gradle4-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle4-
        
    - name: Build Async
      run: |
        ./gradlew clean build --stacktrace

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: async-artifact
        path: 'build/libs/*.jar'
      
